version: '3.7'
services:
  tcc2-frontend:
    build: .
    container_name: tcc2-frontend
    volumes:
       - .:/tcc2-frontend
    working_dir: /tcc2-frontend
    ports:
    - 8080:8080
    command: ['yarn', 'serve']
    